### ISSUE TITLE
wrong reference to express-recorder.js file

### ISSUE THREAD

**Issue by zoharbabin** [kaltura-vpaas/example-tikrok#1]
https://github.com/kaltura-vpaas/example-tikrok/blob/07c623c32ab024af6cdff80778c551e7c790d3bf/views/record.ejs#L13

@hunterpp - shouldn't that line refer to this file: [`kaltura-canvas-express-recorder.js`](https://github.com/kaltura-vpaas/example-tikrok/blob/main/public/kaltura-canvas-express-recorder.js) ?
I don't see in the public folder a file named `express-recorder.js` .

Thanks @jessp01 for finding (and FYI).

**Comment by h-unterp** [comment]
Fixed.
